#
#spring.datasource.url=jdbc:mysql://root:MxPbswUjZauSvcoXXzeyjXiuUNfdzwpZ@mysql.railway.internal:3306/railway
#spring.datasource.username=root
#spring.datasource.password=root
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true



#spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
#spring.datasource.username=root
#spring.datasource.password=MxPbswUjZauSvcoXXzeyjXiuUNfdzwpZ
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.datasource.url=jdbc:mysql://maglev.proxy.rlwy.net:19515/railway
#spring.datasource.username=root
#spring.datasource.password=MxPbswUjZauSvcoXXzeyjXiuUNfdzwpZ
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

#server.port=${PORT:8080}
spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:47698/railway
#spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:47698/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=DLftVShOzecocSMdbGtcALtqlSdXAIJy


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true






